version: '3'
services:
  product:
    build: './product'
    ports:
    - "8090:8090"
    depends_on:
    - kafka
    environment:
      KAFKA_HOST: 192.168.99.100
      KAFKA_PORT: 9092
  productstore:
    build: './productstore'
    depends_on:
    - kafka
    - redis
    environment:
      REDIS_HOST: 192.168.99.100
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.99.100
      KAFKA_PORT: 9092

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    expose:
    - "9092"
    - "2181"

  redis:
    image: redis
    ports:
    - "6379"
    restart: always