version: '3'
services:
  product:
    build: './product'
    ports:
    - "8090:8090"
    depends_on:
    - kafka

  productstore:
    build: './productstore'
    depends_on:
    - kafka
    - redis

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    expose:
    - "9092"
    - "2181"
    environment:
      ADVERTISED_HOST: 192.168.99.102
      ADVERTISED_PORT: 9092
  redis:
    image: redis
    ports:
    - "6379"
    restart: always