version: '3'
services:
  product:
    build: './product'
    ports:
    - "8090:8090"
    depends_on:
    - kafka
    - mongo
    - mongo-express
    environment:
      MONGO_DB_URI : mongodb://mongo:27017/test
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
  productstore:
    build: './productstore'
    depends_on:
    - kafka
    - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    expose:
    - "9092"
    - "2181"

  redis:
    image: redis
    ports:
    - "6379"
    restart: always

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
