version: '3'
services:
  product:
    build: './product'
    ports:
    - "8090:8090"
    depends_on:
    - kafka
    environment:
      KAFKA_URI: localhost:9092

  productstore:
    build: './productstore'
    depends_on:
    - kafka
    - redis
    environment:
      KAFKA_URI: localhost:9092
      REDIS_URI: localhost:6379

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    expose:
    - "9092"
    - "2181"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: localhost

  redis:
    image: redis
    ports:
    - "6379"

    restart: always