version: '3'
services:
  product:
    build: './product'
    ports:
    - "8090:8090"
    depends_on:
    - kafka
    environment:
<<<<<<< HEAD
      KAFKA_URI: localhost:9092

=======
      KAFKA_HOST: 192.168.99.100
      KAFKA_PORT: 9092
>>>>>>> cc5cfd2f985d445fcfc02c9f001f72ea7752dc8b
  productstore:
    build: './productstore'
    depends_on:
    - kafka
    - redis
    environment:
<<<<<<< HEAD
      KAFKA_URI: localhost:9092
      REDIS_URI: localhost:6379
=======
      REDIS_HOST: 192.168.99.100
      REDIS_PORT: 6379
      KAFKA_HOST: 192.168.99.100
      KAFKA_PORT: 9092
>>>>>>> cc5cfd2f985d445fcfc02c9f001f72ea7752dc8b

  kafka:
    image: spotify/kafka
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    expose:
    - "9092"
    - "2181"
<<<<<<< HEAD
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: localhost
=======
>>>>>>> cc5cfd2f985d445fcfc02c9f001f72ea7752dc8b

  redis:
    image: redis
    ports:
    - "6379"

    restart: always