---
micronaut:
    application:
        name: product
                
#Uncomment to set server port
    server:
        port: 8090

---
kafka:
    bootstrap:
<<<<<<< HEAD
        servers: localhost:9092
=======
        servers: ${KAFKA_HOST:192.168.99.100}:${KAFKA_PORT:9092}
>>>>>>> cc5cfd2f985d445fcfc02c9f001f72ea7752dc8b
