---
micronaut:
    application:
        name: product
                
#Uncomment to set server port
    server:
        port: 8090

---
kafka:
    bootstrap:
        servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
