---
micronaut:
    application:
        name: productStore
                
#Uncomment to set server port
    server:
        port: 8085
redis:
    uri: redis://localhost:6379
    #uri: redis://6WNd0asELP@192.168.99.100:6379
    #uri: redis://192.168.99.100:31246
    timeout: 3s
---
kafka:
    bootstrap:
        servers: localhost:9092