---
micronaut:
    application:
        name: productStore
                
#Uncomment to set server port
    server:
        port: 8085
redis:
    uri: redis://localhost:6379
    #uri: redis://6WNd0asELP@localhost:6379
    #uri: redis://localhost:31246
    timeout: 3s
---
redis:
    uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
kafka:
    bootstrap:
        servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
