---
micronaut:
    application:
        name: productStore
                
#Uncomment to set server port
#    server:
#        port: 8080

---
kafka:
    bootstrap:
        servers: ${ADVERTISED_HOST:192.168.99.102}:${ADVERTISED_PORT:9092}