---
micronaut:
    application:
        name: productStore
                
#Uncomment to set server port
#    server:
#        port: 8080

---
redis:
    uri: redis://${REDIS_HOST:192.168.99.100}:${REDIS_PORT:6379}
kafka:
    bootstrap:
        servers: ${KAFKA_HOST:192.168.99.100}:${KAFKA_PORT:9092}